name: foodgram_workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          pip install -r backend/requirements.txt

      - name: Test with flake8
        run: |
          python -m flake8 

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build and push to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_BACKEND }} backend
          docker push ${{ secrets.DOCKER_BACKEND }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << EOF
          cd foodgram/infra
          sudo docker pull ${{ secrets.DOCKER_BACKEND }}
          sudo docker pull ${{ secrets.DOCKER_FRONTEND }}
          sudo docker-compose stop
          sudo docker-compose rm backend
          rm.env
          touch.env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >>.env
          echo DB_NAME=${{ secrets.DB_NAME }} >>.env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >>.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >>.env
          echo DB_HOST=${{ secrets.HOST }} >>.env
          echo DB_PORT=${{ secrets.PORT }} >>.env
          sudo docker-compose up -d
          EOF

  send-message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Деплой foodgram завершен.

            author: ${{ github.actor }}

            message: ${{ github.event.head_commit.message }}

            link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
